# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DwfMeasureData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataCounter', models.IntegerField(default=0)),
                ('Z', models.TextField(default='')),
                ('R', models.FloatField(default=0.0)),
                ('C', models.FloatField(default=0.0)),
                ('freq', models.IntegerField(default=0)),
                ('channel', models.IntegerField(default='')),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DwfResultData',
            fields=[
                ('dataCounter', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('targetTime', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(default=1)),
                ('freqs', models.TextField(default='')),
                ('channels', models.TextField(default='')),
            ],
        ),
    ]
