# -*- coding: utf-8 -*-

STATE_INITIALIZNG = "initializing"
STATE_READY = "ready"
STATE_SETUP_OK = "setup_ok"
STATE_RUNNING = "running"

RECORD_STATE_ON = "record_on"
RECORD_STATE_OFF = "record_off"

COMMAND_START = 'start'
COMMAND_STOP = 'stop'
COMMAND_CHECKCHIP = 'CheckChip'
COMMAND_SETUP = 'Setup'
COMMAND_CHECKSTATE = 'CheckState'
COMMAND_GET_RESULT_LIST = 'GetResultList'

PARAM_STATE = 'STATE'
PARAM_RECORD_STATE = 'RECORD_STATE'
PARAM_COMMAND = 'COMMAND'
PARAM_CHIPINFO = 'CHIPINFO'
PARAM_CHANNEL = 'CHANNEL'
PARAM_FREQ = 'FREQ'
PARAM_DEADLINE = 'DEADLINE'
PARAM_COUNTER = 'COUNTER'
PARAM_PERIOD = 'PERIOD'
PARAM_RESULT = 'RESULT'
PARAM_START_TIME = 'START_TIME'
PARAM_ERROR = 'ERROR'
